name: Pipeline Sistema Bancario

on:
  push:
    branches: [ "master", "main", "desarrollo" ]
  pull_request:
    branches: [ "master", "main", "desarrollo" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Descargar Codigo de C#
      uses: actions/checkout@v4

    - name: 2. Configurar NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. Configurar Entorno MSBuild (Legacy)
      uses: microsoft/setup-msbuild@v2

    - name: 4. Configurar Gestor de Paquetes NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: 5. Instalar Motor de Pruebas Nativo
      run: nuget install Microsoft.TestPlatform -Version 17.8.0 -OutputDirectory Packages_Test

    - name: 6. Restaurar y Compilar Solucion Completa
      run: |
        nuget restore
        msbuild /p:Configuration=Debug /p:Platform="Any CPU"
      shell: powershell

    - name: 7. Ejecutar Pruebas Unitarias Automatizadas
      run: |
        $vstestPath = Get-ChildItem -Path "Packages_Test" -Filter "vstest.console.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        $targetDll = Get-ChildItem -Filter "*Test*.dll" -Recurse | Where-Object { $_.FullName -like "*bin\Debug*" } | Select-Object -First 1 -ExpandProperty FullName
        Write-Host "Ejecutando pruebas sobre: $targetDll"
        & $vstestPath "$targetDll" /Platform:x64
      shell: powershell
